@startuml
hide circle
skinparam classAttributeIconSize 0
title Objekte

object __regendauer__{
    name = "kurzer Schauer"
    menge = 1
    __
    waitForRainToStop()
    }

object __Temperatur__{
    name = "frost"
    temperatur = 1.0
    __
    getActualTemperature()
    }

object __Pollenflug__{
    name = "Pollenbelastung"
    pollenmenge = 0.0
    __
    getActualPollenConcentration()
    }

@enduml